name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: go-crossbuild
    # You may pin to the exact commit or the version.
      uses: santoshkowshikhr/go-build-deploy@v1.0.4
      with:
        # Comma-separated list of "<kernel>/<arch>" combinations.
        platforms: linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        # Package (directory) in the module to build. By default, builds the module directory.
        package: .tar.gz 
        # Compress each build file inside a ".tar.gz" archive.
        compress: true
        # Binary executable filename and filenames prefix for the build files.
        name: upgopher

